PR #15864: [ROCm] Fixed build breaks.
Imported from GitHub PR https://github.com/openxla/xla/pull/15864

Fixed build breaks caused by:
https://github.com/openxla/xla/commit/e4153a41926ff3d7e4b7f31b59e868145d165a59
https://github.com/openxla/xla/commit/732e7e5eefc21fbba234014a9f05716133de3557

Error messages:
1)
xla/service/gpu/fusions/triton/compilation_pipeline_rocm.cc:25:10: fatal error: xla/service/gpu/fusions/triton/sparse_extensions.h: No such file or directory
[2024-08-06T22:41:10.966Z]    25 | #include "xla/service/gpu/fusions/triton/sparse_extensions.h"
[2024-08-06T22:41:10.966Z]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2024-08-06T22:41:10.966Z] compilation terminated.

2)
ERROR: /tf/xla/xla/xla/service/gpu/autotuning/BUILD:431:11: Compiling xla/service/gpu/autotuning/custom_kernel_fusion_autotuner.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (from target //xla/service/gpu/autotuning:custom_kernel_fusion_autotuner) external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer ... (remaining 45 arguments skipped)
In file included from xla/service/gpu/autotuning/custom_kernel_fusion_autotuner.cc:16:
./xla/service/gpu/autotuning/custom_kernel_fusion_autotuner.h:18:10: fatal error: absl/container/flat_hash_set.h: No such file or directory
   18 | #include "absl/container/flat_hash_set.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Copybara import of the project:

--
3b7037a3de5e4aacf004a722ec87de94268414e0 by Zoran Jovanovic <zjovanov@amd.com>:

[ROCm] Fixed build breaks.

Merging this change closes #15864

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/15864 from ROCm:ci_hotfix_240808 3b7037a3de5e4aacf004a722ec87de94268414e0
PiperOrigin-RevId: 660932072