PR #21191: [xla:cpu] Fix missing header in oneDNN ACL build
Imported from GitHub PR https://github.com/openxla/xla/pull/21191

Fixes build error
```
Compiling src/cpu/jit_utils/jit_utils.cpp failed: (Exit 1): clang failed: error executing command (from target @mkl_dnn_acl_compatible//:mkl_dnn_acl) /usr/lib/llvm-14/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 ... (remaining 126 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/mkl_dnn_acl_compatible/src/cpu/jit_utils/jit_utils.cpp:34:10: fatal error: 'common/ittnotify/jitprofiling.h' file not found
#include "common/ittnotify/jitprofiling.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
INFO: Elapsed time: 524.121s, Critical Path: 452.78s
INFO: 543 processes: 45 internal, 498 linux-sandbox.
FAILED: Build did NOT complete successfully
```
Build step:
bazel build --config=mkl_aarch64_threadpool --test_output=all --spawn_strategy=sandboxed //xla/...
Copybara import of the project:

--
23e8fadc3e88208219e685115435c40674efec43 by Crefeda Rodrigues <crefeda.rodrigues@arm.com>:

[xla:cpu] Fix missing headers in oneDNN ACL build

Signed-off-by: Crefeda Rodrigues <crefeda.rodrigues@arm.com>

Merging this change closes #21191

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/21191 from cfRod:aarch64-xla-build 23e8fadc3e88208219e685115435c40674efec43
PiperOrigin-RevId: 714016521