Remove unused ErrorSpec.
`//xla/tests:collective_ops_test_cpu` fails to build on tensorflow/xla/linux/cpu/build_cpu.

```
xla/tests/collective_ops_test.cc:1438:19: error: unused variable 'es' [-Werror,-Wunused-variable]
 1438 |   const ErrorSpec es{1e-5, 1e-5};
      |                   ^~
xla/tests/collective_ops_test.cc:1489:19: error: unused variable 'es' [-Werror,-Wunused-variable]
 1489 |   const ErrorSpec es{1e-5, 1e-5};
      |                   ^~
2 errors generated.
```

PiperOrigin-RevId: 704893145